server {
    #executa na porta 80
    listen 80;

    location / {
        #requisições que batem aqui são encaminhadas pro container na porta 8080
        proxy_pass http://http-server-projeto-korp:8080;

        #repassa o host original da req pro container
        proxy_set_header Host $host;

        #repassa o IP real do client pro go não ver so o ip do nginx
        proxy_set_header X-Real-IP $remote_addr;
    }
}